### ISSUE TITLE
existential operator translation

### ISSUE THREAD

**Issue by jharris119** [HipsterBrown/espresso#27] opened 2016-08-24 14:47 UTC
This line of coffeescript:

``` coffee
includeCancel = @wizardState().includeCancel?=true
```

is getting transpiled into this javascript, which has syntax errors:

``` js
var includeCancel = var base = this.wizardState(); != null ? base.includeCancel : base.includeCancel = true;
```

**Comment by HipsterBrown** [comment] 2016-08-24 15:30
Closing as duplicate of #16.

Thanks for letting me know @jharris119. 👍

**Closed as completed by HipsterBrown** 2016-08-24 15:30 UTC
